spring.application.name=backend

# Port dynamique Railway
server.port=${PORT:8080}

# Connexion PostgreSQL Railway
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=wUAmcXnTkaBsiafrhHQEqHyOFYNSUZLo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10

# Configuration Mail (récupérée depuis les variables Railway)
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT (récupéré depuis les variables Railway)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Frontend URL (Ton domaine !)
app.frontend-url=https://solvhub.fr

# Cloudinary (récupéré depuis les variables Railway)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}