spring.application.name=backend

# Port dynamique Railway
server.port=${PORT:8080}

# Connexion PostgreSQL Railway
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=wUAmcXnTkaBsiafrhHQEqHyOFYNSUZLo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10

# Configuration Mail Resend (Port 587 avec STARTTLS - Recommandé)
resend.api.key=${RESEND_API_KEY:}
# JWT (récupéré depuis les variables Railway)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Frontend URL (Ton domaine !)
app.frontend-url=https://solvhub.fr

# Cloudinary (récupéré depuis les variables Railway)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# google auth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# faire confiance aux en-têtes du proxy et de générer la bonne URL en HTTPS sans le port 8080
server.forward-headers-strategy=framework